import { integer, serial, timestamp } from "drizzle-orm/pg-core";

export const id = serial("id").primaryKey();
export const created_at = timestamp("created_at").defaultNow();
export const updated_at = timestamp("updated_at").defaultNow();
export const deleted_at = timestamp("deleted_at");
export const permissionsEnum = [
  "dashboard:access",
  "dashboard:view",
  "posts:create",
  "posts:edit",
  "posts:delete",
  "posts:publish",
  "posts:read",
  "posts:schedule",
  "posts:review",
  "posts:bulk_actions",
  "users:read",
  "users:write",
  "users:delete",
  "roles:read",
  "roles:write",
  "roles:delete",
  "media:upload",
  "media:read",
  "media:delete",
  "settings:read",
  "settings:write",
  "comments:create",
  "comments:moderate",
  "comments:delete",
  "newsletters:read",
  "newsletters:write",
  "newsletters:delete",
  "auth:register",
  "auth:login",
  "comments:read",
  "comments:reply",
  "comments:delete",
  "comments:reply",
  "comments:approve",
  "comments:spam",
  "media:edit",
  "categories:read",
  "tags:read",
  "tags:create",
  "categories:create",
  "pages:read",
  "seo:edit",
  "seo:view",
  "analytics:view",
  "analytics:export",
] as const;
export const rolesEnum = [
  "admin",
  "editor",
  "author",
  "contributor",
  "moderator",
  "seo_manager",
  "newsletter_manager",
  "subscriber",
  "public",
] as const;
